<?php
/**
 * Fictional demo catalogue.
 *
 * @package BoneHornCrafts\Core
 */

declare( strict_types = 1 );

namespace BoneHornCrafts\Core\Demo;

defined( 'ABSPATH' ) || exit;

/**
 * The demo product dataset.
 *
 * Everything in this file is fictional: the products, SKUs, prices, lot
 * references and copy were written for this reference build. No third-party
 * product data, imagery or review content is used anywhere in the demo.
 *
 * The data is deterministic — same SKUs, same prices, same order every run — so
 * `wp bhc demo seed` is idempotent and re-seeding produces no diff noise.
 */
final class ProductCatalog {

	/**
	 * Category tree: slug => [name, parent slug, description].
	 *
	 * @return array<string, array{name:string, parent:string, description:string}>
	 */
	public static function categories(): array {
		return [
			'knife-handle-scales'  => [
				'name'        => 'Knife Handle Scales',
				'parent'      => '',
				'description' => 'Matched handle scales cut, flattened and paired for full tang and hidden tang builds. Every pair is book-matched from one block so grain and colour run together across the handle.',
			],
			'bone-scales'          => [
				'name'        => 'Bone Scales',
				'parent'      => 'knife-handle-scales',
				'description' => 'Camel and cattle bone scales in smooth, jigged and dyed stabilized finishes. Dense, stable and easy to work with hand tools or a belt grinder.',
			],
			'horn-scales'          => [
				'name'        => 'Horn Scales',
				'parent'      => 'knife-handle-scales',
				'description' => 'Water buffalo and rams horn scales, from deep black polished slabs to bark-edge pieces that keep the natural outer surface of the horn.',
			],
			'wood-acrylic-scales'  => [
				'name'        => 'Wood &amp; Acrylic Scales',
				'parent'      => 'knife-handle-scales',
				'description' => 'Stabilized burls, tropical hardwoods and cast acrylics for makers who want colour and figure without the movement of untreated timber.',
			],
			'guitar-parts'         => [
				'name'        => 'Guitar Parts',
				'parent'      => '',
				'description' => 'Nut and saddle blanks, bridge pin stock and pick blanks in bone and buffalo horn — oversized so you can cut, slot and sand to your own spec.',
			],
			'pen-blanks'           => [
				'name'        => 'Pen Blanks',
				'parent'      => '',
				'description' => 'Turning blanks in bone, horn, stabilized burl and acrylic, squared and sized for standard pen kits.',
			],
			'drinking-horns-mugs'  => [
				'name'        => 'Drinking Horns &amp; Mugs',
				'parent'      => '',
				'description' => 'Food-safe finished drinking horns, tankards and shot sets for reenactment, gifting and display.',
			],
			'combs-beads-cutlery'  => [
				'name'        => 'Combs, Beads &amp; Cutlery',
				'parent'      => '',
				'description' => 'Finished pieces from the same material stock: hand-cut combs, bone folders, beads, shoe horns and horn cutlery.',
			],
			'workshop-essentials'  => [
				'name'        => 'Workshop Essentials',
				'parent'      => '',
				'description' => 'Pin stock, spacer sheet, buttons and small stock that finish a build once the scales are shaped.',
			],
		];
	}

	/**
	 * Merchandising tags: slug => name.
	 *
	 * @return array<string, string>
	 */
	public static function tags(): array {
		return [
			'matched-pair'        => 'Matched Pair',
			'natural-edge'        => 'Natural Edge',
			'viking-medieval'     => 'Viking &amp; Medieval',
			'workshop-essential'  => 'Workshop Essential',
			'bulk-buy'            => 'Bulk Buy',
			'luthier'             => 'Luthier',
			'edc-build'           => 'EDC Build',
			'gift-ready'          => 'Gift Ready',
			'beginner-friendly'   => 'Beginner Friendly',
			'small-batch'         => 'Small Batch',
		];
	}

	/**
	 * Care copy per material family, shown on the product page.
	 *
	 * @return array<string, string>
	 */
	public static function care_notes(): array {
		return [
			'bone'    => 'Work bone dry and slow. Keep a fan or extraction running while sanding, wet-sand from 400 to 1500 grit, then buff with a clean cotton wheel. A wipe of mineral oil every few months keeps the surface from drying out.',
			'horn'    => 'Horn moves with heat and moisture. Keep grinding passes light, dunk in water between passes, and let the piece cool before you clamp it. Finish with 1500 grit and a light wax; avoid dishwashers and direct sun.',
			'wood'    => 'Stabilized blanks need no sealing, but they cut cleanest with sharp tooling and light passes. Finish to 800 grit, then buff. Untreated hardwood should be oiled after shaping and again once the build is together.',
			'acrylic' => 'Cut acrylic slowly to avoid heat cracks, sand wet from 400 to 2000 grit and finish on a loose cotton wheel with plastic polish. Do not use solvent cleaners on the finished handle.',
			'brass'   => 'Deburr cut ends, sand flush after peening and polish with the handle. Brass darkens with handling; a light metal polish brings it back.',
		];
	}

	/**
	 * The full product dataset.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	public static function products(): array {
		return array_merge(
			self::bone_scales(),
			self::horn_scales(),
			self::wood_and_acrylic_scales(),
			self::guitar_parts(),
			self::pen_blanks(),
			self::drinking_horns(),
			self::combs_beads_cutlery(),
			self::workshop_essentials()
		);
	}

	/**
	 * Bone handle scales.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function bone_scales(): array {
		return [
			[
				'sku'          => 'BHC-BS-1042',
				'name'         => 'White Smooth Camel Bone Knife Scales',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'workshop-essential', 'beginner-friendly' ],
				'price'        => 24.99,
				'sale_price'   => null,
				'stock'        => 46,
				'material'     => 'camel-bone',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.14,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-CB-0412',
				'short'        => 'Dense camel bone, cut in pairs from one block and sanded flat and true — the reference scale for a first bone handle.',
				'intro'        => 'Camel bone is the easiest of the bones to learn on: it is denser than cattle bone, it does not chip at the edges when you drill it, and it takes a polish without filling. These pairs are cut from the shin section, boiled, degreased and dried for eight weeks before they are sawn, so the colour is even and there is no smell when you work them.',
				'bullets'      => [
					'Book-matched pair, flattened on both faces',
					'Ready for pin drilling with no further prep',
					'Even off-white colour with faint natural mottling',
				],
			],
			[
				'sku'          => 'BHC-BS-1048',
				'name'         => 'Dyed Stabilized Jigged Bone Scales - Amber',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'edc-build' ],
				'price'        => 29.99,
				'sale_price'   => 24.99,
				'stock'        => 28,
				'material'     => 'cattle-bone',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'amber',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'jigged',
				'unit'         => 'per matched pair',
				'lead_time'    => 2,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.15,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-CB-0455',
				'short'        => 'Traditional jigging cut by hand, dyed amber and stabilized so the colour sits in the pockets rather than on the surface.',
				'intro'        => 'The jigging is cut on a rotary head one pass at a time, which is why no two pairs carry the same pattern. After cutting, the scales are vacuum stabilized with an amber dye that settles into the low points and leaves the high points lighter — the same contrast you see on a well-used slip joint after a decade in a pocket.',
				'bullets'      => [
					'Hand-cut jigging, no two pairs alike',
					'Vacuum stabilized: no further sealing needed',
					'Dye is through the surface, not a coating',
				],
			],
			[
				'sku'          => 'BHC-BS-1053',
				'name'         => 'Jigged Cattle Bone Scales - Natural White',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'beginner-friendly' ],
				'price'        => 22.99,
				'sale_price'   => null,
				'stock'        => 51,
				'material'     => 'cattle-bone',
				'finish'       => 'jigged',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'jigged',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.13,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-CT-0388',
				'short'        => 'Undyed jigged bone with a bright natural surface — the traditional look for a slip joint or a small hunter.',
				'intro'        => 'Left undyed so the bone can age naturally in the hand. Cattle bone is slightly softer than camel, which makes it forgiving on a first jigged handle: if you sand a high spot flat you can carry on rather than starting over.',
				'bullets'      => [
					'Undyed — colour deepens with use',
					'0.30 in thickness suits slim folder builds',
					'Faces sanded flat, edges left square',
				],
			],
			[
				'sku'          => 'BHC-BS-1061',
				'name'         => 'Aged Bone Scales - Antique Cream',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 26.99,
				'sale_price'   => null,
				'stock'        => 22,
				'material'     => 'cattle-bone',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'cream',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 3,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.14,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-CT-0402',
				'short'        => 'Tea-toned bone with the warm cream cast of a handle that has been carried for twenty years.',
				'intro'        => 'The ageing is done in small batches with a tannin bath rather than pigment, so the tone sits deep in the bone and follows the density of the material — end grain takes it darker, the flats stay lighter. Each pair is dried and re-flattened after toning.',
				'bullets'      => [
					'Tannin toned, not painted',
					'Colour varies slightly pair to pair',
					'Re-flattened after toning so faces stay true',
				],
			],
			[
				'sku'          => 'BHC-BS-1067',
				'name'         => 'Dyed Bone Scales - Forest Green',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'edc-build' ],
				'price'        => 27.99,
				'sale_price'   => null,
				'stock'        => 34,
				'material'     => 'cattle-bone',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'forest-green',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'jigged',
				'unit'         => 'per matched pair',
				'lead_time'    => 2,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.15,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-CT-0421',
				'short'        => 'Deep green dye over jigged cattle bone, stabilized so the colour will not lift when you sand the handle to shape.',
				'intro'        => 'Green is the hardest colour to get right on bone — too little pigment and it reads grey, too much and it goes flat. This batch is dyed twice with a rest in between, which keeps the depth while letting the bone structure show through on the high points.',
				'bullets'      => [
					'Twice-dyed for depth, then stabilized',
					'Colour holds through shaping and sanding',
					'Pairs matched for pattern as well as tone',
				],
			],
			[
				'sku'          => 'BHC-BS-1072',
				'name'         => 'Camel Bone Slab Set - Thick Cut 12mm',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'workshop-essential' ],
				'price'        => 34.99,
				'sale_price'   => null,
				'stock'        => 18,
				'material'     => 'camel-bone',
				'finish'       => 'natural',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => '6x2x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 4,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.28,
				'dimensions'   => [ '6', '2', '0.47' ],
				'lot'          => 'LOT-CB-0430',
				'short'        => 'Oversized 12mm slabs for chef knives and large hunters, with enough thickness to carve a full palm swell.',
				'intro'        => 'Cut from the heaviest sections we get, these slabs give you room to shape rather than just round over. At 12mm you can hollow the underside for a hidden tang or carve a deep swell and still leave 6mm of material at the pins.',
				'bullets'      => [
					'12mm thickness, 6 x 2 in footprint',
					'Enough stock for a carved palm swell',
					'Suits chef, bowie and large hunter patterns',
				],
			],
			[
				'sku'          => 'BHC-BS-1078',
				'name'         => 'Bone Bolster Blocks - Matched Pair',
				'categories'   => [ 'knife-handle-scales', 'bone-scales', 'workshop-essentials' ],
				'tags'         => [ 'matched-pair', 'workshop-essential' ],
				'price'        => 16.99,
				'sale_price'   => null,
				'stock'        => 63,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => 'blank-5x0-75',
				'product_type' => 'knife-scales',
				'shape'        => 'blank',
				'unit'         => 'per pair',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.09,
				'dimensions'   => [ '2.5', '0.75', '0.5' ],
				'lot'          => 'LOT-CT-0396',
				'short'        => 'Short bone blocks for front bolsters and butt caps, sanded to 400 grit and ready to fit.',
				'intro'        => 'Bolster stock is where a handle either lines up or does not, so these are cut square on all six faces and checked with a straight edge before they are packed. Pairs are taken from adjacent cuts so the two ends of a handle match.',
				'bullets'      => [
					'Square on all six faces',
					'Sanded to 400 grit, ready to glue up',
					'Sized for front bolsters and butt caps',
				],
			],
			[
				'sku'          => 'BHC-BS-1085',
				'name'         => 'Dyed Stabilized Bone Scales - Indigo',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 28.99,
				'sale_price'   => 23.99,
				'stock'        => 26,
				'material'     => 'cattle-bone',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'indigo',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'jigged',
				'unit'         => 'per matched pair',
				'lead_time'    => 2,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.15,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-CT-0447',
				'short'        => 'Indigo over jigged bone: dark in the pockets, near-white on the ridges, with no two pairs the same.',
				'intro'        => 'A small run dyed with the same indigo bath used for our comb stock. On jigged bone the result is high contrast — the ridges sand back almost white while the cut pockets hold the colour, so the pattern reads clearly even after the handle is shaped.',
				'bullets'      => [
					'High contrast finish on jigged texture',
					'Stabilized after dyeing',
					'Small run — pairs are limited',
				],
			],
			[
				'sku'          => 'BHC-BS-1090',
				'name'         => 'Cattle Bone Scales - Sanded 400 Grit',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'matched-pair', 'beginner-friendly', 'bulk-buy' ],
				'price'        => 19.99,
				'sale_price'   => null,
				'stock'        => 88,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.13,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-CT-0374',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 10, 'price' => 17.49 ],
					[ 'min_qty' => 25, 'price' => 15.99 ],
					[ 'min_qty' => 50, 'price' => 14.49 ],
				],
				'short'        => 'The workshop staple: plain bone, sanded to 400 grit, priced for classes and batch builds.',
				'intro'        => 'This is the pair we cut most of. Nothing decorative — flat faces, square edges, consistent thickness — which is exactly what you want when you are teaching a class of twelve or running a batch of the same pattern. Quantity pricing applies automatically in the cart.',
				'bullets'      => [
					'Consistent 0.30 in thickness across the batch',
					'Quantity pricing from 10 pairs',
					'Used by teaching workshops and batch builders',
				],
			],
			[
				'sku'          => 'BHC-BS-1096',
				'name'         => 'Bone Scale Seconds Pack - Workshop Grade',
				'categories'   => [ 'knife-handle-scales', 'bone-scales' ],
				'tags'         => [ 'bulk-buy', 'beginner-friendly' ],
				'price'        => 12.99,
				'sale_price'   => null,
				'stock'        => 40,
				'material'     => 'cattle-bone',
				'finish'       => 'natural',
				'application'  => 'knife-making',
				'colour'       => 'cream',
				'size'         => '4-5x1-25x0-25',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'pack of 3 pairs',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.32,
				'dimensions'   => [ '4.5', '1.25', '0.25' ],
				'lot'          => 'LOT-CT-SEC-11',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 5, 'price' => 11.49 ],
					[ 'min_qty' => 12, 'price' => 9.99 ],
				],
				'short'        => 'Three pairs of honest seconds — small pits, off-colour patches or a short edge — at practice pricing.',
				'intro'        => 'Every batch produces pieces that miss our first grade for cosmetic reasons: a pit near an edge, a grey streak, a pair that is 2mm short. They still cut, drill and polish the same, so they go out as a practice pack rather than into the bin. Expect visible flaws; that is the point.',
				'bullets'      => [
					'Three pairs per pack, sizes vary slightly',
					'Cosmetic seconds — structurally sound',
					'Ideal for practising jigging and dyeing',
				],
			],
		];
	}

	/**
	 * Horn handle scales.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function horn_scales(): array {
		return [
			[
				'sku'          => 'BHC-HS-2010',
				'name'         => 'Water Buffalo Horn Knife Scales - Black',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'edc-build', 'workshop-essential' ],
				'price'        => 26.99,
				'sale_price'   => null,
				'stock'        => 57,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'knife-making',
				'colour'       => 'black',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.16,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-WB-1180',
				'short'        => 'Solid black buffalo horn, cut from the dense base section and flattened in pairs.',
				'intro'        => 'Horn from the base of the horn is the densest material we cut and it polishes to a depth that no acrylic matches. These pairs are selected for even colour: no grey banding, no light streaks at the edges. If you want the banding, look at our marbled grade instead.',
				'bullets'      => [
					'Cut from the dense base section',
					'Even black through the thickness',
					'Polishes to a mirror without filler',
				],
			],
			[
				'sku'          => 'BHC-HS-2016',
				'name'         => 'Buffalo Horn Bark Scales - Natural Edge',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'natural-edge', 'small-batch', 'viking-medieval' ],
				'price'        => 32.99,
				'sale_price'   => null,
				'stock'        => 21,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'bark-natural-edge',
				'application'  => 'knife-making',
				'colour'       => 'charcoal',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 3,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.17,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-WB-1204',
				'limited'      => true,
				'short'        => 'The outer surface of the horn left intact — ridged, matte and different on every pair.',
				'intro'        => 'Bark scales keep the outer skin of the horn, so the ridges and growth lines that formed on the animal stay on the handle. Only the inside face is flattened. Because the outer surface is what it is, thickness varies across the piece and no two pairs can be matched to each other.',
				'bullets'      => [
					'Outer bark surface untouched',
					'Inside face flattened for glue-up',
					'Thickness varies 8-11mm across the piece',
				],
			],
			[
				'sku'          => 'BHC-HS-2021',
				'name'         => 'Rams Horn Natural Scales',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 49.99,
				'sale_price'   => null,
				'stock'        => 15,
				'material'     => 'rams-horn',
				'finish'       => 'natural',
				'application'  => 'knife-making',
				'colour'       => 'honey',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 5,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.14,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-RH-0331',
				'short'        => 'Honey and amber rams horn with the ripple that only sheep horn gives — the traditional choice for a sheffield-pattern hunter.',
				'intro'        => 'Rams horn is thinner and more figured than buffalo, with translucent honey areas that light passes through at the edges. Yield is low: one horn gives perhaps two usable pairs, which is why it costs what it does. Pairs are cut adjacent so the ripple lines carry across the handle.',
				'bullets'      => [
					'Translucent honey and amber figure',
					'Adjacent cuts so the ripple continues across the handle',
					'Low yield material — availability varies by season',
				],
			],
			[
				'sku'          => 'BHC-HS-2027',
				'name'         => 'Buffalo Horn Scales - Marbled Grey',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'edc-build' ],
				'price'        => 29.99,
				'sale_price'   => null,
				'stock'        => 33,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'knife-making',
				'colour'       => 'marbled',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 1,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.16,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-WB-1219',
				'short'        => 'Grey and black banding running the length of the scale, polished to show the depth of the figure.',
				'intro'        => 'Marbled horn comes from the mid-section where the black and grey layers alternate. Held to the light the bands sit at different depths, which is what gives the handle movement as you turn it. Pairs are matched so the banding mirrors across the blade.',
				'bullets'      => [
					'Banding mirrors across the pair',
					'Mid-section horn, 9-10mm thick',
					'Polished to 1500 grit before packing',
				],
			],
			[
				'sku'          => 'BHC-HS-2033',
				'name'         => 'Buffalo Horn Slabs - Thick 15mm',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'workshop-essential' ],
				'price'        => 39.99,
				'sale_price'   => null,
				'stock'        => 19,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'black',
				'size'         => '6x2x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 4,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.34,
				'dimensions'   => [ '6', '2', '0.59' ],
				'lot'          => 'LOT-WB-1226',
				'short'        => 'Heavy 15mm slabs for carved handles, integral bolsters and hidden tang work.',
				'intro'        => 'Thick stock changes what you can do with horn: you can carve a swell, cut a bolster from the same piece as the scale, or hollow the back for a hidden tang. Cutting this thickness means selecting the largest horns in a delivery, so quantities are limited each month.',
				'bullets'      => [
					'15mm finished thickness',
					'Large enough for carved or integral work',
					'Selected from the largest horns in each delivery',
				],
			],
			[
				'sku'          => 'BHC-HS-2038',
				'name'         => 'Rams Horn Scales - Premium Grade',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 69.99,
				'sale_price'   => null,
				'stock'        => 8,
				'material'     => 'rams-horn',
				'finish'       => 'hand-polished',
				'application'  => 'knife-making',
				'colour'       => 'amber',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 6,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.14,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-RH-0344',
				'limited'      => true,
				'badges'       => [ 'workshop-pick' ],
				'short'        => 'The pairs we set aside: heavy ripple, clean translucent amber and no filled voids.',
				'intro'        => 'Out of a season of rams horn, a small number of pairs come out with strong ripple and no soft core showing at the edge. Those get set aside, polished by hand and sold as premium grade. When they are gone the listing goes out of stock until the next season.',
				'bullets'      => [
					'Hand polished, no filled voids',
					'Strong ripple across both scales',
					'Very limited — one lot per season',
				],
			],
			[
				'sku'          => 'BHC-HS-2044',
				'name'         => 'Buffalo Horn Bolster Stock',
				'categories'   => [ 'knife-handle-scales', 'horn-scales', 'workshop-essentials' ],
				'tags'         => [ 'workshop-essential', 'bulk-buy' ],
				'price'        => 14.99,
				'sale_price'   => null,
				'stock'        => 72,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'sanded-400-grit',
				'application'  => 'knife-making',
				'colour'       => 'black',
				'size'         => 'blank-5x0-75',
				'product_type' => 'knife-scales',
				'shape'        => 'blank',
				'unit'         => 'per pair',
				'lead_time'    => 0,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.1,
				'dimensions'   => [ '2.5', '0.75', '0.5' ],
				'lot'          => 'LOT-WB-1233',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 10, 'price' => 12.99 ],
					[ 'min_qty' => 25, 'price' => 11.49 ],
				],
				'short'        => 'Square-cut horn blocks for bolsters, butt caps and spacer stacks.',
				'intro'        => 'Black horn against a light scale is the oldest contrast in cutlery, and this is the stock for it. Blocks are square on all faces so they sit flat in a stack, and they are sold in pairs so a front and rear bolster come from the same piece of horn.',
				'bullets'      => [
					'Square on all faces for stacked spacers',
					'Sold in pairs from the same block',
					'Quantity pricing from 10 pairs',
				],
			],
			[
				'sku'          => 'BHC-HS-2050',
				'name'         => 'Horn Scale Pack - Mixed Tones (5 Pairs)',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'bulk-buy', 'workshop-essential' ],
				'price'        => 89.99,
				'sale_price'   => 79.99,
				'stock'        => 24,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'two-tone',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'pack of 5 pairs',
				'lead_time'    => 2,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.82,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-WB-1241',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 3, 'price' => 74.99 ],
					[ 'min_qty' => 6, 'price' => 69.99 ],
				],
				'short'        => 'Five matched pairs across black, marbled and honey tones — a season of builds in one box.',
				'intro'        => 'Assembled for makers who work through material rather than buying a pair at a time. Each pack holds five matched pairs chosen across the tonal range we cut that month, so you get black, grey-marbled and honey-translucent scales without ordering three times.',
				'bullets'      => [
					'Five matched pairs, tones vary by month',
					'Packed with lot references for each pair',
					'Trade pricing from three packs',
				],
			],
			[
				'sku'          => 'BHC-HS-2055',
				'name'         => 'Buffalo Horn Scales - Honey Translucent',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 34.99,
				'sale_price'   => null,
				'stock'        => 17,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'knife-making',
				'colour'       => 'honey',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 3,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.14,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-WB-1248',
				'short'        => 'Pale horn cut from the tip section, translucent enough to glow at the edges under a lamp.',
				'intro'        => 'The tip of the horn is thinner and lighter than the base, and when it is sanded down to scale thickness it turns translucent. Against a light liner it reads amber; against black it goes deep gold. Yield per horn is small, so this listing runs in short batches.',
				'bullets'      => [
					'Tip-section horn, translucent at the edges',
					'Pairs cut adjacent for matching tone',
					'Short batches, restocked as horns are cut',
				],
			],
			[
				'sku'          => 'BHC-HS-2061',
				'name'         => 'Rams Horn Bark Scales - Natural Edge',
				'categories'   => [ 'knife-handle-scales', 'horn-scales' ],
				'tags'         => [ 'natural-edge', 'small-batch', 'viking-medieval' ],
				'price'        => 59.99,
				'sale_price'   => null,
				'stock'        => 9,
				'material'     => 'rams-horn',
				'finish'       => 'bark-natural-edge',
				'application'  => 'knife-making',
				'colour'       => 'two-tone',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 6,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.15,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-RH-0352',
				'limited'      => true,
				'short'        => 'Rams horn with the ridged outer surface left on — the look most people picture when they think of a Norse-style handle.',
				'intro'        => 'The growth ridges on a ram horn are deeper and more irregular than buffalo bark, and they run at an angle across the piece. Only the glue face is flattened. Each pair is photographed and lot-referenced before packing because these genuinely cannot be replaced like for like.',
				'bullets'      => [
					'Ridged natural outer surface retained',
					'Glue face flattened, outer face untouched',
					'One-off pairs — lot reference on the packing slip',
				],
			],
		];
	}

	/**
	 * Wood and acrylic handle scales.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function wood_and_acrylic_scales(): array {
		return [
			[
				'sku'          => 'BHC-WS-3012',
				'name'         => 'Stabilized Maple Burl Knife Scales',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'edc-build' ],
				'price'        => 44.99,
				'sale_price'   => null,
				'stock'        => 24,
				'material'     => 'stabilized-wood',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'amber',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 2,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.12,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-MB-0207',
				'short'        => 'Dense maple burl, vacuum stabilized with amber resin so the eyes stay sharp and the blank stays put.',
				'intro'        => 'Burl is only worth using if it is properly stabilized — untreated it moves with the seasons and pulls away from the pins. These blanks are dried to under 8% moisture, vacuum impregnated with resin and heat cured, which makes them behave like a dense plastic on the grinder while still looking like wood.',
				'bullets'      => [
					'Vacuum stabilized and heat cured',
					'Dried below 8% before treatment',
					'Sands to a finish without sealer',
				],
			],
			[
				'sku'          => 'BHC-WS-3018',
				'name'         => 'Stabilized Buckeye Burl Scales - Blue',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 54.99,
				'sale_price'   => null,
				'stock'        => 12,
				'material'     => 'stabilized-wood',
				'finish'       => 'dyed-stabilized',
				'application'  => 'knife-making',
				'colour'       => 'indigo',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 3,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.11,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-BB-0118',
				'limited'      => true,
				'short'        => 'Open-grain buckeye burl dyed deep blue, with the dark inclusions left visible rather than filled flat.',
				'intro'        => 'Buckeye takes dye unevenly, which is the whole point: the soft areas drink the colour and the hard figure stays pale, so the contrast follows the grain instead of covering it. Inclusions and voids are stabilized in place rather than filled, so the surface keeps its texture.',
				'bullets'      => [
					'Dye follows the grain density',
					'Inclusions stabilized, not filled flat',
					'Lightweight — good for a slim EDC handle',
				],
			],
			[
				'sku'          => 'BHC-WS-3023',
				'name'         => 'Indian Rosewood Knife Scales',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'beginner-friendly' ],
				'price'        => 24.99,
				'sale_price'   => null,
				'stock'        => 48,
				'material'     => 'hardwood',
				'finish'       => 'natural',
				'application'  => 'knife-making',
				'colour'       => 'charcoal',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.13,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-RW-0562',
				'short'        => 'Straight-grained rosewood with the natural oil content that makes it feel warm in the hand.',
				'intro'        => 'Rosewood has been the default kitchen-knife handle in this part of the world for a century, and it holds up: oily, stable once seasoned, and it burnishes rather than scratches. These are quarter-sawn so the grain runs straight along the handle.',
				'bullets'      => [
					'Quarter-sawn, straight grain along the handle',
					'Naturally oily — finishes with wax alone',
					'Seasoned 18 months before cutting',
				],
			],
			[
				'sku'          => 'BHC-WS-3029',
				'name'         => 'Ebony Knife Scales - Jet Black',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 39.99,
				'sale_price'   => null,
				'stock'        => 16,
				'material'     => 'hardwood',
				'finish'       => 'hand-polished',
				'application'  => 'knife-making',
				'colour'       => 'black',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 3,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.15,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-EB-0089',
				'short'        => 'Dense black ebony, sanded to 800 grit and buffed — no dye, no filler.',
				'intro'        => 'Ebony is heavy, close-grained and finishes to a near-glass surface with nothing but abrasive and a cotton wheel. It is also brittle at the edges, so these are cut slightly oversize to give you room to work in from the corners.',
				'bullets'      => [
					'Undyed — colour is the timber itself',
					'Cut oversize to allow for edge chipping',
					'Finishes to a gloss with abrasive alone',
				],
			],
			[
				'sku'          => 'BHC-WS-3035',
				'name'         => 'Acrylic Knife Scales - Ocean Swirl',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'beginner-friendly', 'edc-build' ],
				'price'        => 18.99,
				'sale_price'   => null,
				'stock'        => 62,
				'material'     => 'acrylic',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'indigo',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '39269099',
				'gst'          => 18,
				'pair_matched' => true,
				'family'       => 'acrylic',
				'weight'       => 0.18,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-AC-0771',
				'short'        => 'Cast acrylic with blue and white swirl, fully waterproof and dimensionally stable.',
				'intro'        => 'Acrylic is the sensible choice for a knife that will get wet — a fishing or kitchen blade — and it is forgiving to learn on because it sands predictably. Cut it slowly: acrylic melts before it burns, and a fast pass on a belt will smear rather than remove.',
				'bullets'      => [
					'Waterproof and dimensionally stable',
					'Polishes to a high gloss with plastic compound',
					'Cut slowly to avoid heat smear',
				],
			],
			[
				'sku'          => 'BHC-WS-3041',
				'name'         => 'Acrylic Scales - Ivory Alternative',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'beginner-friendly' ],
				'price'        => 16.99,
				'sale_price'   => null,
				'stock'        => 70,
				'material'     => 'acrylic',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'cream',
				'size'         => '5x1-5x0-3',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 0,
				'hsn'          => '39269099',
				'gst'          => 18,
				'pair_matched' => true,
				'family'       => 'acrylic',
				'weight'       => 0.17,
				'dimensions'   => [ '5', '1.5', '0.30' ],
				'lot'          => 'LOT-AC-0783',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 10, 'price' => 14.99 ],
					[ 'min_qty' => 25, 'price' => 13.49 ],
				],
				'short'        => 'Cream cast acrylic with fine grain lines — the modern stand-in for antique ivory, with none of the legal problems.',
				'intro'        => 'Cast with faint parallel grain lines so it reads as aged material rather than plastic at arm\'s length. We stock it because restorers keep asking for a legal, consistent substitute when they replace a damaged handle on an old knife.',
				'bullets'      => [
					'Faint grain lines cast into the material',
					'Consistent colour batch to batch',
					'Quantity pricing for restoration work',
				],
			],
			[
				'sku'          => 'BHC-WS-3047',
				'name'         => 'Stabilized Walnut Scales',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'matched-pair', 'workshop-essential' ],
				'price'        => 29.99,
				'sale_price'   => 25.99,
				'stock'        => 31,
				'material'     => 'stabilized-wood',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'honey',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'per matched pair',
				'lead_time'    => 1,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.12,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-WN-0341',
				'short'        => 'Figured walnut, stabilized clear so the grain reads exactly as it did in the plank.',
				'intro'        => 'Stabilized without dye, because walnut does not need help. The resin fills the open pores and stops the seasonal movement, but the colour stays the mid-brown with dark streaks that made you pick walnut in the first place.',
				'bullets'      => [
					'Clear stabilized — no dye added',
					'Open pores filled, movement stopped',
					'Pairs cut sequentially from one board',
				],
			],
			[
				'sku'          => 'BHC-WS-3052',
				'name'         => 'Wood Scale Sampler - Four Species',
				'categories'   => [ 'knife-handle-scales', 'wood-acrylic-scales' ],
				'tags'         => [ 'bulk-buy', 'gift-ready', 'beginner-friendly' ],
				'price'        => 79.99,
				'sale_price'   => null,
				'stock'        => 20,
				'material'     => 'stabilized-wood',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'two-tone',
				'size'         => '5x1-5x0-375',
				'product_type' => 'knife-scales',
				'shape'        => 'scale',
				'unit'         => 'pack of 4 pairs',
				'lead_time'    => 2,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.52,
				'dimensions'   => [ '5', '1.5', '0.375' ],
				'lot'          => 'LOT-MX-0093',
				'badges'       => [ 'workshop-pick' ],
				'short'        => 'Four matched pairs — maple burl, walnut, rosewood and ebony — for makers deciding what they like to work.',
				'intro'        => 'Four species, four pairs, one box. Nobody can tell you which timber suits your grinder, your finish and your hand; you find out by cutting all four. Each pair ships with its species name and lot reference so you can reorder the one you got on with.',
				'bullets'      => [
					'Maple burl, walnut, rosewood, ebony',
					'Each pair labelled with species and lot',
					'Reorder codes included on the packing slip',
				],
			],
		];
	}

	/**
	 * Guitar and luthier parts.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function guitar_parts(): array {
		return [
			[
				'sku'          => 'BHC-GP-4010',
				'name'         => 'Bone Guitar Nut &amp; Saddle Blank Set',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'workshop-essential', 'beginner-friendly' ],
				'price'        => 12.99,
				'sale_price'   => null,
				'stock'        => 120,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'guitar-luthier',
				'colour'       => 'natural-white',
				'size'         => 'nut-blank',
				'product_type' => 'nut-saddle',
				'shape'        => 'blank',
				'unit'         => 'set of 2 blanks',
				'lead_time'    => 0,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.04,
				'dimensions'   => [ '1.77', '0.35', '0.24' ],
				'lot'          => 'LOT-GN-0611',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 10, 'price' => 11.49 ],
					[ 'min_qty' => 25, 'price' => 9.99 ],
					[ 'min_qty' => 50, 'price' => 8.99 ],
				],
				'short'        => 'Unbleached bone nut and saddle blanks, cut oversize so you can fit them to your own slot.',
				'intro'        => 'Unbleached bone outperforms bleached: bleaching leaves the material lighter but more porous, and porous bone soaks up string energy. These blanks are degreased rather than bleached, cut oversize on every dimension, and left at 400 grit so glue and slotting compounds still key to the surface.',
				'bullets'      => [
					'Unbleached, degreased bone',
					'Nut blank 45 x 6 x 9mm, saddle 80 x 3 x 10mm',
					'Oversize for hand fitting',
				],
			],
			[
				'sku'          => 'BHC-GP-4015',
				'name'         => 'Buffalo Horn Bridge Pin Blanks (Set of 6)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'workshop-essential' ],
				'price'        => 14.99,
				'sale_price'   => null,
				'stock'        => 84,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'smooth',
				'application'  => 'guitar-luthier',
				'colour'       => 'black',
				'size'         => 'blank-5x0-75',
				'product_type' => 'bridge-pin-blank',
				'shape'        => 'blank',
				'unit'         => 'set of 6 blanks',
				'lead_time'    => 1,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.05,
				'dimensions'   => [ '1.4', '0.31', '0.31' ],
				'lot'          => 'LOT-BP-0455',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 6, 'price' => 13.49 ],
					[ 'min_qty' => 20, 'price' => 11.99 ],
				],
				'short'        => 'Square horn blanks for turning your own bridge pins, six to a set with material to spare.',
				'intro'        => 'Turning your own pins means you can match the taper to your bridge instead of shimming a shop-bought set. Blanks are cut square and slightly long so they can be held in a collet and parted off after shaping.',
				'bullets'      => [
					'Six blanks, cut long for collet work',
					'Dense base-section horn',
					'Turns cleanly at moderate speed',
				],
			],
			[
				'sku'          => 'BHC-GP-4021',
				'name'         => 'Bone Bridge Pin Blanks (Set of 6)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier' ],
				'price'        => 13.99,
				'sale_price'   => null,
				'stock'        => 76,
				'material'     => 'cattle-bone',
				'finish'       => 'smooth',
				'application'  => 'guitar-luthier',
				'colour'       => 'natural-white',
				'size'         => 'blank-5x0-75',
				'product_type' => 'bridge-pin-blank',
				'shape'        => 'blank',
				'unit'         => 'set of 6 blanks',
				'lead_time'    => 1,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.05,
				'dimensions'   => [ '1.4', '0.31', '0.31' ],
				'lot'          => 'LOT-BP-0461',
				'short'        => 'Bone pin blanks for players who want the brighter attack bone gives over plastic or horn.',
				'intro'        => 'Bone pins sit brighter and more immediate than horn, which suits a fingerstyle instrument with a dark top. Same dimensions as our horn blanks, so you can turn a set of each and swap them to hear the difference before committing.',
				'bullets'      => [
					'Same blank dimensions as the horn set',
					'Brighter attack than horn or plastic',
					'Degreased, not bleached',
				],
			],
			[
				'sku'          => 'BHC-GP-4026',
				'name'         => 'Bone Saddle Blanks - Oversize (Pack of 3)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'workshop-essential' ],
				'price'        => 16.99,
				'sale_price'   => null,
				'stock'        => 58,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'guitar-luthier',
				'colour'       => 'natural-white',
				'size'         => 'saddle-blank',
				'product_type' => 'nut-saddle',
				'shape'        => 'blank',
				'unit'         => 'pack of 3 blanks',
				'lead_time'    => 0,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.06,
				'dimensions'   => [ '3.15', '0.12', '0.39' ],
				'lot'          => 'LOT-GS-0288',
				'short'        => 'Three oversize saddle blanks, tall enough to reset action on a guitar that has taken on belly.',
				'intro'        => 'A standard saddle blank runs out of height the moment you need to correct a bellied top. These are cut 10mm tall and 80mm long so there is material left after you have set the radius and the compensation.',
				'bullets'      => [
					'10mm tall — room to reset action',
					'80mm long, trims to any bridge',
					'Three per pack for setup work',
				],
			],
			[
				'sku'          => 'BHC-GP-4032',
				'name'         => 'Horn Nut Blanks - Black (Pack of 5)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'bulk-buy' ],
				'price'        => 19.99,
				'sale_price'   => null,
				'stock'        => 44,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'sanded-400-grit',
				'application'  => 'guitar-luthier',
				'colour'       => 'black',
				'size'         => 'nut-blank',
				'product_type' => 'nut-saddle',
				'shape'        => 'blank',
				'unit'         => 'pack of 5 blanks',
				'lead_time'    => 1,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.08,
				'dimensions'   => [ '1.77', '0.35', '0.24' ],
				'lot'          => 'LOT-GN-0623',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 4, 'price' => 17.99 ],
					[ 'min_qty' => 10, 'price' => 15.99 ],
				],
				'short'        => 'Black horn nut blanks in a five pack, for repair benches that fit several a week.',
				'intro'        => 'Horn slots more smoothly than bone under a nut file and is kinder to a fretless or a slotted headstock where you are working close to finish. Five to a pack because a working bench never fits just one.',
				'bullets'      => [
					'Slots smoothly under a nut file',
					'Five blanks per pack',
					'Consistent thickness for repeat setups',
				],
			],
			[
				'sku'          => 'BHC-GP-4038',
				'name'         => 'Bone Pick Blanks - 3mm (Pack of 4)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'gift-ready' ],
				'price'        => 9.99,
				'sale_price'   => null,
				'stock'        => 96,
				'material'     => 'cattle-bone',
				'finish'       => 'smooth',
				'application'  => 'guitar-luthier',
				'colour'       => 'cream',
				'size'         => 'one-size',
				'product_type' => 'pick-blank',
				'shape'        => 'round',
				'unit'         => 'pack of 4 blanks',
				'lead_time'    => 0,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.03,
				'dimensions'   => [ '1.3', '1.1', '0.12' ],
				'lot'          => 'LOT-PK-0197',
				'short'        => 'Flat bone blanks for shaping your own picks — file the profile, bevel the tip, polish.',
				'intro'        => 'A bone pick sounds nothing like nylon: harder attack, faster release, and it wears to the shape of your hand over a few months. These blanks are 3mm flat stock, big enough for a standard 351 outline with room to bevel.',
				'bullets'      => [
					'3mm flat stock, four per pack',
					'Large enough for a 351 outline',
					'File, bevel and polish to your own shape',
				],
			],
			[
				'sku'          => 'BHC-GP-4043',
				'name'         => 'Buffalo Horn Pick Blanks (Pack of 4)',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'gift-ready' ],
				'price'        => 10.99,
				'sale_price'   => null,
				'stock'        => 88,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'guitar-luthier',
				'colour'       => 'black',
				'size'         => 'one-size',
				'product_type' => 'pick-blank',
				'shape'        => 'round',
				'unit'         => 'pack of 4 blanks',
				'lead_time'    => 0,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.03,
				'dimensions'   => [ '1.3', '1.1', '0.12' ],
				'lot'          => 'LOT-PK-0203',
				'short'        => 'Horn pick blanks — warmer than bone, with enough flex at 3mm to soften the attack.',
				'intro'        => 'Horn has a little give that bone does not, so the attack is rounder and the pick is quieter against wound strings. Polished on both faces before packing so you only need to shape the outline and bevel.',
				'bullets'      => [
					'Warmer, softer attack than bone',
					'Faces polished before packing',
					'Four blanks per pack',
				],
			],
			[
				'sku'          => 'BHC-GP-4049',
				'name'         => 'Luthier Starter Kit - Bone Nut, Saddle &amp; Pins',
				'categories'   => [ 'guitar-parts' ],
				'tags'         => [ 'luthier', 'gift-ready', 'workshop-essential' ],
				'price'        => 34.99,
				'sale_price'   => 29.99,
				'stock'        => 37,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'guitar-luthier',
				'colour'       => 'natural-white',
				'size'         => 'one-size',
				'product_type' => 'nut-saddle',
				'shape'        => 'blank',
				'unit'         => 'kit',
				'lead_time'    => 1,
				'hsn'          => '92099900',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.12,
				'dimensions'   => [ '3.15', '1.2', '0.5' ],
				'lot'          => 'LOT-GK-0142',
				'badges'       => [ 'workshop-pick' ],
				'short'        => 'Everything bone for one acoustic upgrade: nut blank, oversize saddle blank and six pin blanks.',
				'intro'        => 'The parts most players change first, in one box. Swapping plastic for bone at the nut, saddle and pins is the cheapest real change you can make to an entry-level acoustic, and doing all three at once means one setup instead of three.',
				'bullets'      => [
					'One nut blank, one oversize saddle blank, six pin blanks',
					'All from the same degreased bone stock',
					'Enough material to fit without shimming',
				],
			],
		];
	}

	/**
	 * Pen turning blanks.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function pen_blanks(): array {
		return [
			[
				'sku'          => 'BHC-PB-5010',
				'name'         => 'Camel Bone Pen Blanks (Pair)',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'matched-pair', 'workshop-essential' ],
				'price'        => 15.99,
				'sale_price'   => null,
				'stock'        => 64,
				'material'     => 'camel-bone',
				'finish'       => 'natural',
				'application'  => 'pen-turning',
				'colour'       => 'natural-white',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'pair of blanks',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'bone',
				'weight'       => 0.07,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0512',
				'short'        => 'Square bone blanks sized for a standard two-barrel kit, cut from one piece so both halves match.',
				'intro'        => 'Bone turns like a hard hardwood: it cuts cleanly with a skew, it does not tear out, and it takes a polish straight off the tool. Both blanks in a pair come from the same section so the colour and density match barrel to barrel.',
				'bullets'      => [
					'Both barrels from one section',
					'Sized for standard two-barrel kits',
					'Turns and polishes without filler',
				],
			],
			[
				'sku'          => 'BHC-PB-5016',
				'name'         => 'Buffalo Horn Pen Blanks (Pair)',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'matched-pair' ],
				'price'        => 17.99,
				'sale_price'   => null,
				'stock'        => 52,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'smooth',
				'application'  => 'pen-turning',
				'colour'       => 'black',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'pair of blanks',
				'lead_time'    => 1,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'horn',
				'weight'       => 0.08,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0518',
				'short'        => 'Black horn blanks that finish to a deep gloss without any coating at all.',
				'intro'        => 'Horn is the material to reach for when you want a pen that feels warm rather than cold in the hand. Turn it wet or with light passes; the surface burnishes under the tool and needs nothing beyond micromesh and a wax.',
				'bullets'      => [
					'Finishes with micromesh and wax alone',
					'Warm in the hand, unlike resin',
					'Matched pair from one horn',
				],
			],
			[
				'sku'          => 'BHC-PB-5022',
				'name'         => 'Stabilized Burl Pen Blanks - Amber',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'matched-pair', 'small-batch' ],
				'price'        => 22.99,
				'sale_price'   => null,
				'stock'        => 29,
				'material'     => 'stabilized-wood',
				'finish'       => 'dyed-stabilized',
				'application'  => 'pen-turning',
				'colour'       => 'amber',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'pair of blanks',
				'lead_time'    => 2,
				'hsn'          => '44219990',
				'gst'          => 12,
				'pair_matched' => true,
				'family'       => 'wood',
				'weight'       => 0.06,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0524',
				'short'        => 'Amber-dyed burl, stabilized right through so even the soft eyes turn cleanly.',
				'intro'        => 'Untreated burl is a gamble on a pen: the soft eyes tear out at exactly the wrong moment. Stabilizing fills them, so the blank cuts uniformly and the figure stays sharp under the finish rather than blurring.',
				'bullets'      => [
					'Soft eyes filled by stabilizing resin',
					'Cuts uniformly across the figure',
					'Amber dye deepens the contrast',
				],
			],
			[
				'sku'          => 'BHC-PB-5027',
				'name'         => 'Rams Horn Pen Blank - Single',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'small-batch' ],
				'price'        => 26.99,
				'sale_price'   => null,
				'stock'        => 14,
				'material'     => 'rams-horn',
				'finish'       => 'natural',
				'application'  => 'pen-turning',
				'colour'       => 'honey',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'single blank',
				'lead_time'    => 4,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.05,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0531',
				'limited'      => true,
				'short'        => 'A single rams horn blank with translucent honey figure — enough for one barrel or a full slimline.',
				'intro'        => 'Sold singly because that is how the material comes: a ram horn rarely yields two blanks with the same figure. Best used where the whole barrel is visible, so the ripple runs the length of the pen rather than being cut in half by a centre band.',
				'bullets'      => [
					'Sold as a single blank',
					'Translucent honey figure',
					'Suits slimline and single-barrel kits',
				],
			],
			[
				'sku'          => 'BHC-PB-5033',
				'name'         => 'Acrylic Pen Blank Bundle (Set of 5)',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'bulk-buy', 'beginner-friendly' ],
				'price'        => 24.99,
				'sale_price'   => null,
				'stock'        => 41,
				'material'     => 'acrylic',
				'finish'       => 'smooth',
				'application'  => 'pen-turning',
				'colour'       => 'two-tone',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'set of 5 blanks',
				'lead_time'    => 0,
				'hsn'          => '39269099',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'acrylic',
				'weight'       => 0.24,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0537',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 4, 'price' => 22.49 ],
					[ 'min_qty' => 10, 'price' => 19.99 ],
				],
				'short'        => 'Five cast acrylic blanks in mixed colours — the practice set for learning speed and finish.',
				'intro'        => 'Cheap enough to make mistakes on, which is exactly what you need when you are learning where the heat builds. Colours are mixed from the current casting run, so the set that arrives will not be identical to the photograph.',
				'bullets'      => [
					'Five blanks, mixed colours from the current run',
					'Forgiving material for practice',
					'Quantity pricing for classes',
				],
			],
			[
				'sku'          => 'BHC-PB-5039',
				'name'         => 'Bone Pen Blank Bulk Pack (10 Blanks)',
				'categories'   => [ 'pen-blanks' ],
				'tags'         => [ 'bulk-buy', 'workshop-essential' ],
				'price'        => 59.99,
				'sale_price'   => null,
				'stock'        => 26,
				'material'     => 'cattle-bone',
				'finish'       => 'natural',
				'application'  => 'pen-turning',
				'colour'       => 'natural-white',
				'size'         => 'blank-5x0-75',
				'product_type' => 'pen-blank',
				'shape'        => 'blank',
				'unit'         => 'pack of 10 blanks',
				'lead_time'    => 2,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.36,
				'dimensions'   => [ '5', '0.75', '0.75' ],
				'lot'          => 'LOT-PB-0544',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 3, 'price' => 54.99 ],
					[ 'min_qty' => 6, 'price' => 49.99 ],
				],
				'short'        => 'Ten bone blanks at trade pricing, for turners selling at markets and shows.',
				'intro'        => 'Bought by turners who run a table at weekend shows and get through a box a month. Blanks are cut to the same nominal size, but colour varies across the pack the way natural material does — nobody wants ten identical pens on one table anyway.',
				'bullets'      => [
					'Ten blanks per pack',
					'Colour varies naturally across the pack',
					'Trade pricing from three packs',
				],
			],
		];
	}

	/**
	 * Drinking horns and mugs.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function drinking_horns(): array {
		return [
			[
				'sku'          => 'BHC-DH-6010',
				'name'         => 'Viking Drinking Horn with Stand',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'viking-medieval', 'gift-ready' ],
				'price'        => 49.99,
				'sale_price'   => 44.99,
				'stock'        => 38,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'marbled',
				'size'         => 'one-size',
				'product_type' => 'drinking-horn',
				'shape'        => 'horn',
				'unit'         => 'horn and stand',
				'lead_time'    => 2,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.62,
				'dimensions'   => [ '14', '5', '5' ],
				'lot'          => 'LOT-DH-0288',
				'badges'       => [ 'workshop-pick' ],
				'short'        => 'A 400ml polished horn with a turned hardwood stand, finished food-safe inside and out.',
				'intro'        => 'Cleaned, boiled and polished, then sealed inside with a food-grade lining so it holds a drink without taking on the taste of the horn. The stand is turned from the same rosewood we cut handle scales from, and the horn sits in it at an angle that keeps a full pour level.',
				'bullets'      => [
					'Approximately 400ml capacity',
					'Food-safe lining, hand wash only',
					'Turned rosewood stand included',
				],
			],
			[
				'sku'          => 'BHC-DH-6016',
				'name'         => 'Polished Drinking Horn - 350ml',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'viking-medieval', 'gift-ready' ],
				'price'        => 34.99,
				'sale_price'   => null,
				'stock'        => 45,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'black',
				'size'         => 'one-size',
				'product_type' => 'drinking-horn',
				'shape'        => 'horn',
				'unit'         => 'each',
				'lead_time'    => 1,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.38,
				'dimensions'   => [ '12', '4.5', '4.5' ],
				'lot'          => 'LOT-DH-0294',
				'short'        => 'The plain horn: 350ml, polished, lined and ready to use, without the stand.',
				'intro'        => 'For events where a stand is one more thing to carry. Same preparation as our stand set — boiled, scraped, polished and lined — in a slightly smaller capacity that is easier to hold through a long evening.',
				'bullets'      => [
					'Approximately 350ml capacity',
					'Polished outer surface, lined interior',
					'No stand — supplied on its own',
				],
			],
			[
				'sku'          => 'BHC-DH-6021',
				'name'         => 'Horn Tankard with Handle - 500ml',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'viking-medieval', 'gift-ready' ],
				'price'        => 69.99,
				'sale_price'   => null,
				'stock'        => 22,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'marbled',
				'size'         => 'one-size',
				'product_type' => 'horn-mug',
				'shape'        => 'round',
				'unit'         => 'each',
				'lead_time'    => 4,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.74,
				'dimensions'   => [ '6', '5', '4.5' ],
				'lot'          => 'LOT-DH-0301',
				'short'        => 'A half-litre horn tankard with a fitted base and a riveted horn handle.',
				'intro'        => 'Built rather than carved: the body is a horn section pressed round, the base is a horn disc fitted and sealed, and the handle is cut from a separate piece and riveted through. It stands on a table, which a drinking horn famously does not.',
				'bullets'      => [
					'500ml, stands upright on its own base',
					'Riveted horn handle',
					'Hand wash, do not soak',
				],
			],
			[
				'sku'          => 'BHC-DH-6027',
				'name'         => 'Drinking Horn Shot Set (Set of 4)',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'gift-ready', 'viking-medieval' ],
				'price'        => 39.99,
				'sale_price'   => null,
				'stock'        => 34,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'two-tone',
				'size'         => 'one-size',
				'product_type' => 'drinking-horn',
				'shape'        => 'bead',
				'unit'         => 'set of 4',
				'lead_time'    => 2,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.3,
				'dimensions'   => [ '3', '2', '2' ],
				'lot'          => 'LOT-DH-0309',
				'short'        => 'Four small horn cups, each around 40ml, in mixed natural tones.',
				'intro'        => 'Cut from the tips, which are too small for a full horn and too good to waste. Every set comes out different because the tips do: expect one dark, one pale and two somewhere between.',
				'bullets'      => [
					'Four cups, approximately 40ml each',
					'Mixed natural tones in every set',
					'Boxed for gifting',
				],
			],
			[
				'sku'          => 'BHC-DH-6032',
				'name'         => 'Carved Norse Drinking Horn',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'viking-medieval', 'small-batch', 'gift-ready' ],
				'price'        => 89.99,
				'sale_price'   => null,
				'stock'        => 7,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'charcoal',
				'size'         => 'one-size',
				'product_type' => 'drinking-horn',
				'shape'        => 'horn',
				'unit'         => 'each',
				'lead_time'    => 7,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.66,
				'dimensions'   => [ '15', '5', '5' ],
				'lot'          => 'LOT-DH-0316',
				'limited'      => true,
				'short'        => 'Knotwork carved by hand around the rim and along the spine, cut into the horn rather than printed on it.',
				'intro'        => 'The carving is done with rotary burrs by one of our finishers, working from a drawn layout rather than a transfer, which is why the knot spacing shifts slightly as it follows the curve of the horn. Each piece takes most of a day, so they are made in small numbers.',
				'bullets'      => [
					'Hand-carved knotwork, cut into the horn',
					'Around 450ml capacity',
					'Made in small numbers — allow a week to dispatch',
				],
			],
			[
				'sku'          => 'BHC-DH-6038',
				'name'         => 'Horn Mug - Natural Marbled 400ml',
				'categories'   => [ 'drinking-horns-mugs' ],
				'tags'         => [ 'gift-ready' ],
				'price'        => 59.99,
				'sale_price'   => 49.99,
				'stock'        => 25,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'smooth',
				'application'  => 'home-table',
				'colour'       => 'marbled',
				'size'         => 'one-size',
				'product_type' => 'horn-mug',
				'shape'        => 'round',
				'unit'         => 'each',
				'lead_time'    => 3,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.58,
				'dimensions'   => [ '5', '4.5', '4' ],
				'lot'          => 'LOT-DH-0322',
				'short'        => 'A straight-sided horn mug with heavy grey-and-black marbling, sized for a normal drink.',
				'intro'        => 'Chosen from the marbled sections rather than the plain black, so the banding wraps around the body. The wall is left thicker than our tankard, which makes it heavier in the hand and slower to warm a cold drink.',
				'bullets'      => [
					'400ml, straight-sided',
					'Heavy marbled banding around the body',
					'Thicker wall than the tankard',
				],
			],
		];
	}

	/**
	 * Combs, beads and cutlery.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function combs_beads_cutlery(): array {
		return [
			[
				'sku'          => 'BHC-CB-7010',
				'name'         => 'Hand-Polished Horn Beard Comb',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready', 'viking-medieval' ],
				'price'        => 16.99,
				'sale_price'   => null,
				'stock'        => 92,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'black',
				'size'         => 'one-size',
				'product_type' => 'comb',
				'shape'        => 'comb',
				'unit'         => 'each',
				'lead_time'    => 0,
				'hsn'          => '96151900',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.04,
				'dimensions'   => [ '4', '2.4', '0.15' ],
				'lot'          => 'LOT-CM-0740',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 12, 'price' => 14.49 ],
					[ 'min_qty' => 36, 'price' => 12.49 ],
				],
				'short'        => 'Saw-cut horn teeth, rounded and polished by hand so nothing snags — the difference from a moulded comb.',
				'intro'        => 'Every tooth is cut on a saw, then the tip and both edges are rounded on a wheel and polished. That hand work is the whole product: a moulded plastic comb has a seam down each tooth, and horn cut without rounding will pull. Horn also carries less static than plastic, which is why barbers still ask for it.',
				'bullets'      => [
					'Saw-cut teeth, hand rounded and polished',
					'Anti-static compared with moulded plastic',
					'Trade pricing from 12 pieces',
				],
			],
			[
				'sku'          => 'BHC-CB-7015',
				'name'         => 'Bone Hair Comb - Fine Tooth',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready' ],
				'price'        => 14.99,
				'sale_price'   => null,
				'stock'        => 78,
				'material'     => 'cattle-bone',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'cream',
				'size'         => 'one-size',
				'product_type' => 'comb',
				'shape'        => 'comb',
				'unit'         => 'each',
				'lead_time'    => 0,
				'hsn'          => '96151900',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.04,
				'dimensions'   => [ '5', '1.8', '0.12' ],
				'lot'          => 'LOT-CM-0746',
				'short'        => 'Close-spaced bone teeth for fine hair, cut from a single flat piece with no join.',
				'intro'        => 'Fine-tooth combs live or die on tooth spacing: too wide and they do nothing, too close and they snap. This spacing has been our standard for years — close enough to work, thick enough at the root that the teeth survive being dropped.',
				'bullets'      => [
					'Cut from one flat piece, no join',
					'Close spacing for fine hair',
					'Teeth thickened at the root',
				],
			],
			[
				'sku'          => 'BHC-CB-7021',
				'name'         => 'Wooden Comb - Neem Wood',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready', 'beginner-friendly' ],
				'price'        => 12.99,
				'sale_price'   => null,
				'stock'        => 110,
				'material'     => 'hardwood',
				'finish'       => 'natural',
				'application'  => 'home-table',
				'colour'       => 'honey',
				'size'         => 'one-size',
				'product_type' => 'comb',
				'shape'        => 'comb',
				'unit'         => 'each',
				'lead_time'    => 0,
				'hsn'          => '96151900',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'wood',
				'weight'       => 0.03,
				'dimensions'   => [ '6', '2', '0.2' ],
				'lot'          => 'LOT-CM-0752',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 12, 'price' => 10.99 ],
					[ 'min_qty' => 48, 'price' => 8.99 ],
				],
				'short'        => 'Wide-tooth neem comb, sanded smooth and left unfinished so the wood keeps its own smell.',
				'intro'        => 'Neem is the traditional comb wood here and it stays the best value piece we sell. Nothing is applied to it — no lacquer, no oil — because the point of a neem comb is the untreated wood against the scalp.',
				'bullets'      => [
					'Untreated neem, no lacquer or oil',
					'Wide spacing for thick or curly hair',
					'Trade pricing from 12 pieces',
				],
			],
			[
				'sku'          => 'BHC-CB-7026',
				'name'         => 'Horn Bead Assortment (50 Beads)',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'bulk-buy', 'viking-medieval' ],
				'price'        => 22.99,
				'sale_price'   => null,
				'stock'        => 47,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'jewellery',
				'colour'       => 'two-tone',
				'size'         => 'one-size',
				'product_type' => 'bead',
				'shape'        => 'bead',
				'unit'         => 'bag of 50',
				'lead_time'    => 1,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.16,
				'dimensions'   => [ '0.4', '0.4', '0.4' ],
				'lot'          => 'LOT-BD-0193',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 5, 'price' => 20.49 ],
					[ 'min_qty' => 15, 'price' => 17.99 ],
				],
				'short'        => 'Fifty drilled horn beads in mixed shapes and tones, 8-12mm, for beard rings, cord work and jewellery.',
				'intro'        => 'Turned, drilled and tumbled in batches, then mixed so a bag carries the full tonal range from black through grey to honey. Hole size is consistent at 3mm even where the bead diameters vary, so they thread onto the same cord.',
				'bullets'      => [
					'Fifty beads, 8-12mm, mixed tones',
					'Consistent 3mm drilled hole',
					'Tumble polished, ready to thread',
				],
			],
			[
				'sku'          => 'BHC-CB-7032',
				'name'         => 'Bone Folder - Leather Craft Tool',
				'categories'   => [ 'combs-beads-cutlery', 'workshop-essentials' ],
				'tags'         => [ 'workshop-essential', 'beginner-friendly' ],
				'price'        => 18.99,
				'sale_price'   => null,
				'stock'        => 66,
				'material'     => 'cattle-bone',
				'finish'       => 'hand-polished',
				'application'  => 'leather-work',
				'colour'       => 'natural-white',
				'size'         => 'one-size',
				'product_type' => 'bone-folder',
				'shape'        => 'blank',
				'unit'         => 'each',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.05,
				'dimensions'   => [ '6', '1', '0.3' ],
				'lot'          => 'LOT-BF-0421',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 6, 'price' => 16.99 ],
					[ 'min_qty' => 20, 'price' => 14.99 ],
				],
				'short'        => 'A real bone folder — one pointed end, one rounded — polished so it burnishes leather and creases paper without marking.',
				'intro'        => 'Plastic folders drag and leave a shine; bone slides and burnishes. This one is shaped from solid bone with a fine point for corners and a broad rounded end for creasing spines and setting edges. It gets better as it wears in.',
				'bullets'      => [
					'Solid bone, not resin or plastic',
					'Pointed end for corners, rounded end for creasing',
					'Polished to 2000 grit so it will not mark leather',
				],
			],
			[
				'sku'          => 'BHC-CB-7038',
				'name'         => 'Horn Shoe Horn - 16 inch',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready' ],
				'price'        => 24.99,
				'sale_price'   => null,
				'stock'        => 39,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'black',
				'size'         => 'one-size',
				'product_type' => 'shoe-horn',
				'shape'        => 'blank',
				'unit'         => 'each',
				'lead_time'    => 1,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.12,
				'dimensions'   => [ '16', '2', '0.3' ],
				'lot'          => 'LOT-SH-0164',
				'short'        => 'A long horn shoe horn with a hanging hole, shaped so it flexes without folding.',
				'intro'        => 'Sixteen inches so you can use it standing up. Horn is the right material for this job precisely because it flexes a little and springs back; a rigid plastic one cracks at the neck after a winter of boots.',
				'bullets'      => [
					'16 in length — use standing',
					'Flexes and springs back rather than cracking',
					'Drilled and finished for hanging',
				],
			],
			[
				'sku'          => 'BHC-CB-7043',
				'name'         => 'Horn Cutlery Set - Six Piece',
				'categories'   => [ 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready', 'small-batch' ],
				'price'        => 79.99,
				'sale_price'   => null,
				'stock'        => 16,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'marbled',
				'size'         => 'one-size',
				'product_type' => 'cutlery',
				'shape'        => 'blank',
				'unit'         => 'set of 6',
				'lead_time'    => 5,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.31,
				'dimensions'   => [ '8', '1.5', '0.4' ],
				'lot'          => 'LOT-CU-0077',
				'short'        => 'Three forks and three spoons carved from marbled horn, for serving rather than cutting.',
				'intro'        => 'Horn does not react with food, does not scratch a serving bowl and does not conduct heat, which is why it has been used for table pieces for centuries. This set is carved rather than pressed, so each handle follows the curve the horn already had.',
				'bullets'      => [
					'Three forks, three spoons',
					'Carved individually — shapes vary slightly',
					'Hand wash only, do not soak or heat',
				],
			],
		];
	}

	/**
	 * Workshop consumables and small stock.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private static function workshop_essentials(): array {
		return [
			[
				'sku'          => 'BHC-WE-8010',
				'name'         => 'Brass Pin Stock - 3mm (Pack of 5)',
				'categories'   => [ 'workshop-essentials' ],
				'tags'         => [ 'workshop-essential', 'bulk-buy', 'beginner-friendly' ],
				'price'        => 8.99,
				'sale_price'   => null,
				'stock'        => 140,
				'material'     => 'brass-pin-stock',
				'finish'       => 'smooth',
				'application'  => 'knife-making',
				'colour'       => 'honey',
				'size'         => 'blank-6x1x1',
				'product_type' => 'plate-spacer',
				'shape'        => 'blank',
				'unit'         => 'pack of 5 rods',
				'lead_time'    => 0,
				'hsn'          => '74072100',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'brass',
				'weight'       => 0.09,
				'dimensions'   => [ '6', '0.12', '0.12' ],
				'lot'          => 'LOT-BR-0918',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 10, 'price' => 7.99 ],
					[ 'min_qty' => 30, 'price' => 6.99 ],
				],
				'short'        => 'Five 150mm brass rods at 3mm — the standard pin for scales up to 10mm thick.',
				'intro'        => 'Sold long so one rod does a whole knife with offcuts left for a lanyard tube. Diameter is held to 3mm within a hundredth, which matters when you have already drilled the tang.',
				'bullets'      => [
					'Five rods, 150mm each',
					'3mm diameter held to ±0.01mm',
					'Peens cleanly without splitting',
				],
			],
			[
				'sku'          => 'BHC-WE-8015',
				'name'         => 'Horn Spacer Sheet - 2mm',
				'categories'   => [ 'workshop-essentials' ],
				'tags'         => [ 'workshop-essential' ],
				'price'        => 11.99,
				'sale_price'   => null,
				'stock'        => 85,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'sanded-400-grit',
				'application'  => 'knife-making',
				'colour'       => 'black',
				'size'         => 'one-size',
				'product_type' => 'plate-spacer',
				'shape'        => 'scale',
				'unit'         => 'sheet',
				'lead_time'    => 0,
				'hsn'          => '96019010',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.07,
				'dimensions'   => [ '6', '2', '0.08' ],
				'lot'          => 'LOT-SP-0355',
				'short'        => 'Flat black horn sheet at 2mm, for spacer stacks between bolster and scale.',
				'intro'        => 'Cut and sanded parallel so a stack of four sheets is still square. Black horn against a light spacer is the classic stack, and at 2mm you get a definite line without pushing the handle out of proportion.',
				'bullets'      => [
					'2mm, sanded parallel across the sheet',
					'6 x 2 in — enough for several handles',
					'Stacks square with no wedge',
				],
			],
			[
				'sku'          => 'BHC-WE-8021',
				'name'         => 'Bone Spacer Sheet - 3mm',
				'categories'   => [ 'workshop-essentials' ],
				'tags'         => [ 'workshop-essential' ],
				'price'        => 13.99,
				'sale_price'   => null,
				'stock'        => 71,
				'material'     => 'cattle-bone',
				'finish'       => 'sanded-400-grit',
				'application'  => 'knife-making',
				'colour'       => 'natural-white',
				'size'         => 'one-size',
				'product_type' => 'plate-spacer',
				'shape'        => 'scale',
				'unit'         => 'sheet',
				'lead_time'    => 0,
				'hsn'          => '96019090',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.09,
				'dimensions'   => [ '6', '2', '0.12' ],
				'lot'          => 'LOT-SP-0361',
				'short'        => 'White bone sheet at 3mm, the light half of a contrasting spacer stack.',
				'intro'        => 'Cut from the same flat stock as our scales, so the density and colour match if you are stacking bone spacers under bone scales. Thick enough to shape a bevel into the spacer rather than leaving it as a flat line.',
				'bullets'      => [
					'3mm — takes a shaped bevel',
					'Matches our bone scale stock',
					'6 x 2 in sheet',
				],
			],
			[
				'sku'          => 'BHC-WE-8026',
				'name'         => 'Buffalo Horn Buttons (Set of 12)',
				'categories'   => [ 'workshop-essentials', 'combs-beads-cutlery' ],
				'tags'         => [ 'bulk-buy', 'gift-ready' ],
				'price'        => 15.99,
				'sale_price'   => null,
				'stock'        => 58,
				'material'     => 'water-buffalo-horn',
				'finish'       => 'hand-polished',
				'application'  => 'leather-work',
				'colour'       => 'charcoal',
				'size'         => 'one-size',
				'product_type' => 'button',
				'shape'        => 'bead',
				'unit'         => 'set of 12',
				'lead_time'    => 1,
				'hsn'          => '96061000',
				'gst'          => 12,
				'pair_matched' => false,
				'family'       => 'horn',
				'weight'       => 0.06,
				'dimensions'   => [ '0.9', '0.9', '0.15' ],
				'lot'          => 'LOT-BT-0244',
				'wholesale'    => true,
				'tiers'        => [
					[ 'min_qty' => 6, 'price' => 14.49 ],
					[ 'min_qty' => 20, 'price' => 12.99 ],
				],
				'short'        => 'Twelve four-hole horn buttons at 23mm, for coats, leather work and repairs.',
				'intro'        => 'Turned from horn offcuts, drilled four-hole and polished. Tailors buy these because plastic buttons on a wool coat look exactly like plastic buttons on a wool coat; leather workers buy them because horn survives being sewn through heavy thread.',
				'bullets'      => [
					'Twelve buttons, 23mm, four-hole',
					'Tones vary naturally across the set',
					'Trade pricing from six sets',
				],
			],
			[
				'sku'          => 'BHC-WE-8032',
				'name'         => 'Bone Dice Set - Six Piece',
				'categories'   => [ 'workshop-essentials', 'combs-beads-cutlery' ],
				'tags'         => [ 'gift-ready', 'viking-medieval' ],
				'price'        => 26.99,
				'sale_price'   => 22.99,
				'stock'        => 33,
				'material'     => 'cattle-bone',
				'finish'       => 'hand-polished',
				'application'  => 'home-table',
				'colour'       => 'cream',
				'size'         => 'one-size',
				'product_type' => 'dice',
				'shape'        => 'bead',
				'unit'         => 'set of 6',
				'lead_time'    => 2,
				'hsn'          => '95044000',
				'gst'          => 18,
				'pair_matched' => false,
				'family'       => 'bone',
				'weight'       => 0.08,
				'dimensions'   => [ '0.63', '0.63', '0.63' ],
				'lot'          => 'LOT-DC-0058',
				'short'        => 'Six 16mm bone dice with drilled and inked pips, cut square and hand finished.',
				'intro'        => 'Cut from solid bone, squared on a jig and finished by hand, with pips drilled rather than printed and filled with black ink. They are dice made the way dice were made before injection moulding, which means they are not casino-balanced and are not sold as if they were.',
				'bullets'      => [
					'Six dice, 16mm, drilled and inked pips',
					'Hand finished — not machine balanced',
					'Supplied in a drawstring cotton bag',
				],
			],
		];
	}
}
