
const knifeHandle =  ["CATTLE BONE SCALE","WHITE SMOOTH BONE SCALES","DYED STABILIZED BONE SCALES","DYED STABILIZED JIGGED BONE SCALES","WATER BUFFALO HORN SCALES",
		"WATER BUFFALO HORN SCALES","WATER BUFFALO HORN DYED AND JIGGED SCALES","WATER BUFFALO HORN BARK SCALES",
	"RAM’S (SHEEP) HORN SCALE","NATURALHORN ROLLS"]