

export const knifeHandles = {
	"CAMEL & CATTLE BONE SCALE": ['WHITE SMOOTH BONE SCALES','DYED STABILIZED BONE SCALES','DYED STABILIZED JIGGED BONE SCALES','IN STAG BONE SCALES'],
	"WATER BUFFALO HORN SCALES": ['WATER BUFFALO HORN SCALES','WATER BUFFALO HORN DYED AND JIGGED SCALES','WATER BUFFALO HORN BARK SCALES'],
	"RAM'S (SHEEP) HORN SCALE": ['NATURAL HORN SCALES'],
	"ACRYLIC SCALES": [],
	"WOOD SCALES": [],
	"HORN ROLLS": []
}

export const products = {
	"GUITAR PARTS": ['BONE NUT & SADDLES','HORN NUT & SADDLES','BONE PICK BLANKS','HORN PICK BLANKS','BONE BRIDGE PIN BLANKS','PICKS'],
	"HAIR COMBS": ['HORN COMB','MUSTACHE HORN COMB','BONE COMB','HAIR BONE NEEDLE','WOODEN COMB'],
	"PEN BLANKS": ['BONE PEN BLANKS','ACRYLIC PEN BLANKS','HORN PEN BLANKS','WOODEN PEN BLANKS'],
	"BONE & HORN BEADS": ['BONE BEADS','BONE HAIR PIPE BEADS','HORN BEADS','HORN HAIR PIPE BEADS'],
	"DRINKING HORN & MUG": ['DRINKING HORN','HORN MUG'],
	"BONE FOLDER": ['BONE FOLDER','TEFLON BONE FOLDER','SHOE HORN','BULL SHOE HORN'],
	"BULL HORN CUTLERY": ['HORN BOWL','HORN SPOON'],
	"BUFFALO HORN PLATES": ['BONE BUTTONS','BONE PENDANTS'],
	"BONE DICE": [],
	"JEWELLERY": []

}
